# adapted from https://huggingface.co/docs/hub/spaces-github-actions
# requires HF_TOKEN secret configured in repo
# TODO also see: https://github.com/marketplace/actions/sync-with-hugging-face-hub

name: Sync main branch to Hugging Face Hub

on:
  push:
    branches: [main]

  # enable running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://raehik:$HF_TOKEN@huggingface.co/raehik/ss23-ex main
